// front/newFront/fabrica-needs/components/ui/footer.jsx
import { Footer } from "flowbite-react";

export const FooterComponent = () => {
  return (
    <div className="rounded-none">
      <Footer container={true}>
        <div className="flex justify-around items-center container mx-auto">
          <Footer.Copyright
            href="https://www.linkedin.com/in/jo%C3%A3o-felipi-cardoso-a1710522b/"
            by="João Felipi Cardoso -> @snowsr"
            year={2022}
          />
          <Footer.LinkGroup>
            <Footer.Link href="https://github.com/snow-sr/fabrica-needs/tree/react">
              Github
            </Footer.Link>
          </Footer.LinkGroup>
        </div>
      </Footer>
    </div>
  );
};

// front/web/fab/src/components/FooterComponent.vue
<template>
  <footer
    class="p-4 bg-white shadow md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-900"
  >
    <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400"
      >© 2022
      <a href="https://github.com/snow-sr" class="hover:underline">snow-sr</a>
    </span>
  </footer>
</template>
